services:
  hadoop-master:
    image: madjidtaoualit/hadoop-cluster:latest
    container_name: hadoop-master
    hostname: hadoop-master
    networks:
      hadoop:
        ipv4_address: "172.23.0.3"
    ports:
      - "9870:9870"
      - "8088:8088"
      - "7077:7077"
      - "16010:16010"
    command: ["tail", "-f", "/dev/null"]

  hadoop-worker1:
    image: madjidtaoualit/hadoop-cluster:latest
    container_name: hadoop-worker1
    hostname: hadoop-worker1
    networks:
      - hadoop
    ports:
      - "8040:8042"
    command: ["tail", "-f", "/dev/null"]

  hadoop-worker2:
    image: madjidtaoualit/hadoop-cluster:latest
    container_name: hadoop-worker2
    hostname: hadoop-worker2
    networks:
      - hadoop
    ports:
      - "8041:8042"
    command: ["tail", "-f", "/dev/null"]

  api:
    build:
      context: ./api
    container_name: api
    hostname: api
    networks:
      API:
        ipv4_address: "172.23.0.1"
    ports:
      - "3000:3000"
    environment:
      - HDFS_HOST=hadoop-master
      - HDFS_PORT=9870
    command: ["node", "app.js"]

networks:
  hadoop:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/16
  API:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/16
