services:
  hadoop-master:
    image: madjidtaoualit/hadoop-cluster:latest
    container_name: hadoop-master
    hostname: hadoop-master
    networks:
      - hadoop
    ports:
      - "9870:9870"
      - "8088:8088"
      - "7077:7077"
      - "16010:16010"
    command: ["tail", "-f", "/dev/null"]

  hadoop-worker1:
    image: madjidtaoualit/hadoop-cluster:latest
    container_name: hadoop-worker1
    hostname: hadoop-worker1
    networks:
      - hadoop
    ports:
      - "8040:8042"
    command: ["tail", "-f", "/dev/null"]

  hadoop-worker2:
    image: madjidtaoualit/hadoop-cluster:latest
    container_name: hadoop-worker2
    hostname: hadoop-worker2
    networks:
      - hadoop
    ports:
      - "8041:8042"
    command: ["tail", "-f", "/dev/null"]

networks:
  hadoop:
    driver: bridge