project:
  resources:
    - "Data/*"
  type: website

website:
  title: "Projet"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true



